In [1]:
%pwd

'/media/kirti/Dev/MachineLearning/E2EBookRecommenderSystem/notebooks'

In [2]:
%cd ..

/media/kirti/Dev/MachineLearning/E2EBookRecommenderSystem

In [3]:
import numpy as np
import pandas as pd

In [4]:
books = pd.read_csv("./data/Books.csv", low_memory=False)

In [5]:
books.shape

(271360, 8)

In [7]:
books.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='object')

In [8]:
books.head(2)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...

In [14]:
books["Image-URL-L"][10]

'http://images.amazon.com/images/P/0771074670.01.LZZZZZZZ.jpg'

In [15]:
books = books[["ISBN", "Book-Title", "Book-Author", "Year-Of-Publication", "Publisher", "Image-URL-L"]]

In [16]:
books.rename(columns={
    "Book-Title": "Title",
    "Book-Author": "Author",
    "Year-Of-Publication": "Year",
    "Publisher": "Publisher",
    "Image-URL-L": "ImageURL"
}, inplace=True)

/tmp/ipykernel_28624/1699201015.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  books.rename(columns={

In [17]:
books.head()

,ISBN,Title,Author,Year,Publisher,ImageURL
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...

In [19]:
users = pd.read_csv("./data/Users.csv")
users.shape

(278858, 3)

In [20]:
users.columns

Index(['User-ID', 'Location', 'Age'], dtype='object')

In [21]:
users.rename(columns={
    "User-ID": "UserID"
}, inplace=True)

In [22]:
users.head()

   UserID                            Location   Age
0       1                  nyc, new york, usa   NaN
1       2           stockton, california, usa  18.0
2       3     moscow, yukon territory, russia   NaN
3       4           porto, v.n.gaia, portugal  17.0
4       5  farnborough, hants, united kingdom   NaN

In [23]:
ratings = pd.read_csv("./data/Ratings.csv")
ratings.shape

(1149780, 3)

In [24]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [25]:
ratings.rename(columns=
               {"User-ID": "UserID",
               "Book-Rating": "BookRating"}, inplace=True)

In [26]:
ratings.head()

   UserID        ISBN  BookRating
0  276725  034545104X           0
1  276726  0155061224           5
2  276727  0446520802           0
3  276729  052165615X           3
4  276729  0521795028           6

In [27]:
ratings["UserID"].value_counts()

UserID
11676     13602
198711     7550
153662     6109
98391      5891
35859      5850
          ...
116180        1
116166        1
116154        1
116137        1
276723        1
Name: count, Length: 105283, dtype: int64

In [ ]:
x = ratings["UserID"].value_counts() > 50

np.int64(3371)

In [30]:
x[x].shape

(3371,)

In [31]:
y = x[x].index

In [32]:
ratings = ratings[ratings["UserID"].isin(y)]

In [33]:
ratings.shape

(765672, 3)

In [ ]:
books_with_ratings = books.merge(ratings, on="ISBN")

In [35]:
books_with_ratings.head(3)

,ISBN,Title,Author,Year,Publisher,ImageURL,UserID,BookRating
0,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,11400,0
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,11676,8
2,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,85526,0

In [43]:
number_ratings = books_with_ratings.groupby('Title')['BookRating'].count().reset_index()

In [44]:
number_ratings.head()

                                               Title  BookRating
0   A Light in the Storm: The Civil War Diary of ...           4
1                              Always Have Popsicles           1
2               Apple Magic (The Collector's series)           1
3   Ask Lily (Young Women of Faith: Lily Series, ...           1
4   Beyond IBM: Leadership Marketing and Finance ...           1

In [46]:
number_ratings.rename(columns={
    "BookRating": "TotalRatingCount"
},inplace=True)

In [47]:
final_rating = books_with_ratings.merge(number_ratings,on='Title')

In [57]:
final_rating = final_rating[final_rating["TotalRatingCount"] >= 50]

In [48]:
final_rating.head()

,ISBN,Title,Author,Year,Publisher,ImageURL,UserID,BookRating,TotalRatingCount
0,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,11400,0,8
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,11676,8,8
2,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,85526,0,8
3,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,96054,0,8
4,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,116866,9,8

In [53]:
final_rating.drop_duplicates(["UserID", "Title"],inplace=True)

In [58]:
final_rating.isnull().sum()

ISBN                0
Title               0
Author              0
Year                0
Publisher           0
ImageURL            0
UserID              0
BookRating          0
TotalRatingCount    0
dtype: int64

In [93]:
book_pivot = final_rating.pivot_table(index='Title', columns='UserID', values='BookRating', fill_value=0)

In [94]:
book_pivot

UserID,183,243,254,507,626,638,643,741,882,929,...,277928,277965,278026,278137,278144,278188,278418,278582,278633,278843
Title,,,,,,,,,,,,,,,,,,,,,
1984,0.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2010: Odyssey Two,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
204 Rosewood Lane,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24 Hours,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [95]:
from scipy.sparse import csr_matrix

In [96]:
book_sparse = csr_matrix(book_pivot)

In [97]:
book_sparse

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 39301 stored elements and shape (1373, 3221)>

In [98]:
type(book_sparse)

scipy.sparse._csr.csr_matrix

In [99]:
from sklearn.neighbors import NearestNeighbors

In [203]:
model =  NearestNeighbors(algorithm='brute')#, metric='cosine')
model.fit(book_sparse)

NearestNeighbors(algorithm='brute')

In [140]:
# lets extract a book name
book_sample = book_pivot.loc["Harry Potter and the Chamber of Secrets (Book 2)",:].values
book_sample

array([0., 0., 9., ..., 0., 0., 0.], shape=(3221,))

In [153]:
distance,suggestion = model.kneighbors(book_sample.reshape(1,-1), n_neighbors=6)

In [154]:
distance

array([[9.99200722e-16, 3.86105079e-01, 3.99668937e-01, 5.16747093e-01,
        6.05010088e-01, 6.16965454e-01]])

In [155]:
suggestion

array([[437, 440, 438, 441, 442, 439]])

In [162]:
book_names = book_pivot.index

In [167]:
for ind in suggestion[0]:
    print(book_pivot.index[ind])
    # print image url
    print(final_rating[final_rating["Title"] == book_names[ind]]["ImageURL"].values[0])

Harry Potter and the Chamber of Secrets (Book 2)
http://images.amazon.com/images/P/0439064872.01.LZZZZZZZ.jpg
Harry Potter and the Prisoner of Azkaban (Book 3)
http://images.amazon.com/images/P/0439136350.01.LZZZZZZZ.jpg
Harry Potter and the Goblet of Fire (Book 4)
http://images.amazon.com/images/P/0439139597.01.LZZZZZZZ.jpg
Harry Potter and the Sorcerer's Stone (Book 1)
http://images.amazon.com/images/P/0590353403.01.LZZZZZZZ.jpg
Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))
http://images.amazon.com/images/P/059035342X.01.LZZZZZZZ.jpg
Harry Potter and the Order of the Phoenix (Book 5)
http://images.amazon.com/images/P/043935806X.01.LZZZZZZZ.jpg

In [168]:
import pickle

In [ ]:
pickle.dump(model, open("./artifacts/book_recommender_model.pkl", "wb"))
pickle.dump(book_pivot, open("./artifacts/book_pivot.pkl", "wb"))
pickle.dump(final_rating,open("./artifacts/final_rating.pkl","wb"))

### Testing Model

In [204]:
def recommend_book(book_name):
    # try: 
    #     book_index = book_names[book_names == book_name][0][0]
    # except IndexError:
    #     return "Sorry, book not found."
    distance, suggestions = model.kneighbors(book_pivot.loc[book_name,:].values.reshape(1, -1), n_neighbors=6)
    for ind in suggestions[0]:
        if book_pivot.index[ind] == book_name:
            print("Recommended books for '{}':".format(book_name))
        else:
            print(book_pivot.index[ind])
        # print(final_rating[final_rating["Title"] == book_pivot.index[ind]]["ImageURL"].values[0])

In [205]:
recommend_book("2nd Chance")

Recommended books for '2nd Chance':
The Jury
Roses Are Red
The Sky Is Falling
The Vendetta Defense
Thicker Than Water

In [1]:
%pwd

'/media/kirti/Dev/MachineLearning/E2EBookRecommenderSystem/notebooks'

In [2]:
%cd ..

/media/kirti/Dev/MachineLearning/E2EBookRecommenderSystem

In [5]:
import os, sys, shutil

def use_without_training():
    try:
        os.makedirs("artifacts", exist_ok=True)

        for item in os.listdir("backup"):
            src = os.path.join("backup", item)
            dst = os.path.join("artifacts", item)

            if os.path.isdir(src):
                # copy folder recursively
                if os.path.exists(dst):
                    shutil.rmtree(dst)
                shutil.copytree(src, dst)
            else:
                # copy single file
                shutil.copy2(src, dst)

        print("Using existing model from backup folder")

    except Exception as e:
        print(f"Error using existing model: {e}")
        sys.exit(1)

In [6]:
use_without_training()

Using existing model from backup folder